name: Build .NET Framework WinForms App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet CLI
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore "LightWebBrowser.sln"

      - name: Build solution (Release)
        run: msbuild "LightWebBrowser.sln" /p:Configuration=Release /p:Platform="Any CPU"

      - name: Show build output (for debugging)
        run: |
          if exist "LightWebBrowser\bin\Release" (
            dir "LightWebBrowser\bin\Release"
          ) else (
            echo "Release folder not found. Listing entire repo for debugging:"
            dir
          )

      - name: Publish build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: LightWebBrowser-Build
          path: |
            LightWebBrowser\bin\Release\
