name: Build .NET Framework WinForms App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet CLI
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore "LightWebBrowser.sln"

      - name: Build solution (Release)
        run: msbuild "LightWebBrowser.sln" /p:Configuration=Release /p:Platform="Any CPU"

      - name: Get git short hash
        id: get_hash
        run: echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        shell: bash

      - name: Rename exe file with git short hash
        shell: pwsh
        run: |
          $oldPath = "LightWebBrowser\bin\Release\net48\LightWebBrowser.exe"
          $newName = "LightWebBrowser-$env:SHORT_HASH.exe"
          if (Test-Path $oldPath) {
            Rename-Item -Path $oldPath -NewName $newName
            Write-Host "Renamed to $newName"
          } else {
            Write-Host "Executable not found at $oldPath"
            exit 1
          }

      - name: Show build output (for debugging)
        shell: pwsh
        run: Get-ChildItem "LightWebBrowser\bin\Release\net48"

      - name: Publish build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: LightWebBrowser-Build-${{ env.SHORT_HASH }}
          path: LightWebBrowser\bin\Release\net48\
